project_id = "rxvdypoldfxzpfzpduie"

[functions.gamification]
verify_jwt = false

[functions.admin-actions]
verify_jwt = false

[functions.manage-investment]
verify_jwt = false

[functions.payment-password]
verify_jwt = false

[functions.test-commission]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.mercadopago-pix]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-payout]
verify_jwt = false
