// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Evita tela preta por crash silencioso de env ausente em produção
  // eslint-disable-next-line no-console
  console.error("Supabase env missing: VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const SAFE_URL = SUPABASE_URL || "https://example.supabase.co";
const SAFE_KEY = SUPABASE_PUBLISHABLE_KEY || "public-anon-key";

export const supabase = createClient<Database>(SAFE_URL, SAFE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});